// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package portal

var TableNames = struct {
	Apps  string
	Orgs  string
	Users string
}{
	Apps:  "apps",
	Orgs:  "orgs",
	Users: "users",
}
