output      = "models/portal"
wipe        = true
no-tests    = true
no-hooks    = true
pkgname     = "portal"

[psql]
  dbname    = "portal"
  host      = "localhost"
  port      = 5432
  user      = "portal"
  pass      = "portal"
  schema    = "public"
  sslmode   = "disable"
  whitelist = ["pilots", "jets", "languages", "pilot_languages"]
  blacklist = ["migrations", "other"]
