output      = "models"
wipe        = true
no-tests    = true
no-hooks    = true

[psql]
  dbname    = "dbname"
  host      = "localhost"
  port      = 5432
  user      = "dbuser"
  pass      = "dbpasswd"
  schema    = "public"
  sslmode   = "disable"
  whitelist = ["video_tags", "tags", "videos", "sponsors", "users", "type_monsters"]
  blacklist = ["migrations", "other"]
