// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Sponsors     string
	Tags         string
	TypeMonsters string
	Users        string
	VideoTags    string
	Videos       string
}{
	Sponsors:     "sponsors",
	Tags:         "tags",
	TypeMonsters: "type_monsters",
	Users:        "users",
	VideoTags:    "video_tags",
	Videos:       "videos",
}
